config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :activities
  root 'pages#dashboard'
  get 'projetos', to: 'pages#projects'
  get 'dashboard', to: 'pages#dashboard'
  get 'search', to: 'projects#search', as: :search
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :project
  validates :name_activity, uniqueness: { case_sensitive: false }, length: {minimum: 5}
  validates :project_id, :name_activity, :start_date, :end_date, presence: true
  validates :end_date,
            date: { after: :start_date }

  def self.activities_finished
    total = Activity.all
    count = 0
    total.each do |activity|
      count += 1 if activity.finished
    end
    count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :activities, dependent: :destroy
  validates :name, uniqueness: { case_sensitive: false }, length: { minimum: 5 }
  validates :name, :start_date, :end_date, presence: true
  validates :end_date,
            date: { after: :start_date }

  def porcentage
    num_finished = finished_count
    num_total = activities.count
    num_finished * 100 / num_total
  end

  def finished_count
    num_total = activities
    count = 0
    num_total.each do |activity|
      count += 1 if activity.finished
    end
    count
  end

  def late?
    activity = activities
    late = false
    activity.each do |act|
      late = Date.new(act.end_date.to_i).to_time.to_i > Date.new(end_date.to_i).to_time.to_i
    end
    late
  end

  def self.total_late
    count = 0
    Project.all.each do |project|
      count += 1 if project.late?
    end
    count
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show; end

  # GET /activities/new
  def new
    @activity = Activity.new
    @projects = Project.all
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    @projects = Project.all
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity.project, notice: 'Atividade criada com sucesso!' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    @activity.toggle!(:finished)
    redirect_to project_path(@activity.project.id)
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy
    flash[:notice] = 'Atividade apagada com sucesso!'
    redirect_to project_path(@activity.project_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:project_id, :name_activity, :start_date, :end_date, :finished)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_aside

  def set_aside
    @projects_all = Project.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def projects
    @projects = Project.all
  end

  def dashboard
    @total_projects = Project.all.count
    @delayed_projects = Project.total_late
    @in_day = @total_projects - @delayed_projects

    @total_activities = Activity.all.count
    @total_finished = Activity.activities_finished
    @total_open = @total_activities - @total_finished
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Projeto criado com Sucesso'
      redirect_to @project
    else
      render 'new'
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    flash[:notice] = 'Projeto apagado com sucesso!'
    redirect_to projetos_path
  end

  def search
    @query = params[:query]
    if @query.nil?
      flash.now[:alert] = 'Campo em branco'
    else
      @projects = Project.where('name like ?', "%#{@query}%").order(:name)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :start_date, :end_date)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <div class="row">
    <div class="col-6">
      <%= render 'shared/errors', obj: activity %>
      <div class="col-6 fs-3">
        <%= form.label :project_id, class: "form-label" %>
        <%= form.collection_select :project_id, @projects, :id, :name, {}, class: "form-select fs-3 mb-3" %>
      </div>
      <div class="col-6 fs-3">
        <%= form.label :name_activity, class: "form-label" %>
        <%= form.text_field :name_activity, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="col-6 fs-3">
        <%= form.label :start_date, class: "form-label" %>
        <%= form.date_field :start_date, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="col-6 fs-3">
        <%= form.label :end_date, class: "form-label" %>
        <%= form.date_field :end_date, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="text-center col-6">
        <%= form.submit class: "btn btn-primary fs-4" %>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Dashboard</li>
      </ol>
    </div>
  </div>
  <h1>Editing Activity</h1>
  <%= render 'form', activity: @activity %>
  <%= link_to 'Show', @activity %> |
  <%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Atividades</li>
        <%= link_to new_activity_path do %>
          <li class="btn btn-outline-success ms-3 btn-lg"><i class="fa fa-plus me-2 text-success"></i>Nova atividade</li>
        <% end %>
      </ol>
    </div>
  </div>
  <%=  render 'layouts/messages' %>
  <table class="table table-hover text-dark mb-0 bg-white table-striped">
    <thead>
      <tr>
        <th>Nome do Atividade</th>
        <th>Data de Inicio</th>
        <th>Data de Termino</th>
        <th>Finalizada?</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @activities.each do |activity| %>
        <tr>
          <td>
            <%= link_to activity.project, class: "text-dark" do %>
              <i class="fa fa-eye text-primary mx-2"></i>
              <%= activity.name_activity %>
            <% end %>
          </td>
          <td><%= activity.start_date.strftime("%d-%m-%Y")  %></td>
          <td><%= activity.end_date.strftime("%d-%m-%Y") %></td>
          <td>
            <%= activity.finished ? "Sim" : "Não" %>
          </td>
          <td>
            <%= link_to  activity_path(activity), method: :put do %>
              <i class="fa fa-exchange-alt mx-3 fs-3"></i>
            <% end %>
            <%= link_to activity, method: :delete, data: {confirm: "Tem certeza?"} do %>
              <i class="fa fa-window-close text-danger fs-3"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/activities/new.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Atividade</li>
      </ol>
    </div>
  </div>
  <h1>Nova atividade</h1>
  <%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Atividades</li>
      </ol>
    </div>
  </div>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Id project:</strong>
    <%= @activity.project_id %>
  </p>
  <p>
    <strong>Name activity:</strong>
    <%= @activity.name_activity %>
  </p>
  <p>
    <strong>Start date:</strong>
    <%= @activity.start_date.strftime("%d-%m-%Y") %>
  </p>
  <p>
    <strong>End date:</strong>
    <%= @activity.end_date.strftime("%d-%m-%Y") %>
  </p>
  <p>
    <strong>Finished:</strong>
    <%= @activity.finished %>
  </p>
  <%= link_to 'Edit', edit_activity_path(@activity) %> |
  <%= link_to 'Back', activities_path %>

app/views/layouts/_aside.html.erb
<aside>
  <div id="sidebar">
    <ul class="sidebar-menu">
      <li >
        <%= link_to dashboard_path do %>
          <i class="fa fa-adjust"></i>
          <span>Dashboard</span>
        <% end %>
      </li>
      <li>
        <%= link_to projetos_path do %>
          <i class="fa fa-clipboard"></i>
          <span>Projetos</span>
        <% end %>
      </li>
      <% if !@projects_all.empty? %>
        <li >
          <%= link_to activities_path do %>
            <i class="fa fa-tasks"></i>
            <span>Atividades</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</aside>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show text-start mt-2" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 bi" viewBox="0 0 16 16" role="img" aria-label="Success:">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </svg>
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="header dark-bg">
  <div class="d-flex align-items-center ms-4 h-100">
    <div class="pointer">
      <div class="" onclick="button_toogle2()">
        <i class="fa fa-align-justify hover fs-1"></i>
      </div>
    </div>
    <div class="me-4 ms-4">
      <%= link_to "Soft", root_path, class: "navbar-brand  text-danger" %>
    </div>
    <div class="">
      <%= form_with url: "/search", class: "search-row ms-4 d-flex", method: :get do |form| %>
        <%= form.text_field :query, class: "form-control me-1 fs-4", type: "search", placeholder: "Nome do projeto..." %>
        <%= form.button   do %>
          <i class="fa fa-search fs-3"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</header>
<script>
  function button_toogle2 ()  {
    document.getElementById("sidebar").classList.toggle('sidenone')
    document.getElementById("main-content").classList.toggle('main-total')
   };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto - Gestao</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-mutate-approach="sync"></script>
  </head>
</head>
<body id="container">
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/aside' %>
  <section id="main-content">
    <%= yield %>
  </section>
</body>
</html>

app/views/pages/dashboard.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Dashboard</li>
      </ol>
    </div>
  </div>
  <div class="row row-cols-2">
    <div class="col row-chart">
      <div class="myChart">
        <h4 class="text-center fs-3">Projetos</h4>
        <%= pie_chart([
  {name: "Total", data: @total_projects},
  {name: "Atrasados", data: @delayed_projects},
  {name: "Em dia", data: @in_day}
], legend: "left", theme: "rainbow") %>
      </div>
    </div>
    <div class="col row-chart">
      <div class="myChart">
        <h4 class="text-center fs-3">Atividades</h4>
        <%= pie_chart([
  {name: "Total", data: @total_activities},
  {name: "Finalizados", data: @total_finished},
  {name: "Em aberto", data: @total_open}
], legend: "left") %>
      </div>
    </div>
  </div>
</section>

app/views/pages/projects.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Projetos</li>
        <%= link_to new_project_path do %>
          <li class="btn btn-outline-success ms-3 btn-lg"><i class="fa fa-plus me-2 text-success"></i>Novo projeto</li>
        <% end %>
      </ol>
    </div>
  </div>
  <%=  render 'layouts/messages' %>
  <% if @projects.count < 1 %>
    <h2 class="mt-3">Crie seu primeiro projeto para iniciar</h2>
  <% else %>
    <table class="table table-hover text-dark mb-0 bg-white table-striped">
      <thead>
        <tr>
          <th>Nome do Projeto</th>
          <th>Data de Inicio</th>
          <th>Data de Termino</th>
          <th>%Completo</th>
          <th>Atrasado?</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td>
              <%= link_to project, class: "text-dark" do %>
                <i class="fa fa-eye text-primary mx-2"></i>
                <%= project.name %>
              <% end %>
            </td>
            <td>
              <%= project.start_date.strftime("%d-%m-%Y") %>
            </td>
            <td>
              <%= project.end_date.strftime("%d-%m-%Y") %>
            </td>
            <td>
              <% if project.activities.count > 0 %>
                <%=  project.porcentage  %>%
              <% else %>
                0%
              <% end %>
            </td>
            <td>
              <%= project.late? ? "Sim" : "Não" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <div class="row">
    <div class="col-6">
      <%= render 'shared/errors', obj: project %>
      <div class="col-6 fs-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="col-6 fs-3">
        <%= form.label :start_date, class: "form-label" %>
        <%= form.date_field :start_date, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="col-6 fs-3">
        <%= form.label :end_date, class: "form-label" %>
        <%= form.date_field :end_date, class: "form-control mb-3 fs-3" %>
      </div>
      <div class="text-center col-6">
        <%= form.submit class: "btn btn-primary fs-4" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Dashboard</li>
      </ol>
    </div>
  </div>
  <h1>Editing Project</h1>
  <%= render 'form', project: @project %>
  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Dashboard</li>
      </ol>
    </div>
  </div>
  <p id="notice"><%= notice %></p>
  <h1>Projects</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td>
            <%= project.name %>
          </td>
          <td><%= project.start_date.strftime("%d-%m-%Y")  %></td>
          <td><%= project.end_date.strftime("%d-%m-%Y") %></td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Projeto</li>
      </ol>
    </div>
  </div>
  <h1>Novo Projeto</h1>
  <%= render 'form', project: @project %>

app/views/projects/search.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i>Procurar projeto</li>
      </ol>
    </div>
  </div>
  <h1 class="mt-3 mb-3">Projetos com o nome: <%= @query %></h1>
  <%=  render 'layouts/messages' %>
  <% if @projects.count == 0 %>
    <h3 class="text-danger">Nenhum projeto encontrado</h3>
  <% else %>
    <table class="table table-hover text-dark mb-0 bg-white table-striped">
      <thead>
        <tr>
          <th>Nome do Projeto</th>
          <th>Data de Inicio</th>
          <th>Data de Termino</th>
          <th>%Completo</th>
          <th>Atrasado?</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td>
              <%= link_to project, class: "text-dark" do %>
                <i class="fa fa-eye text-primary mx-2"></i>
                <%= project.name %>
              <% end %>
            </td>
            <td>
              <%= project.start_date.strftime("%d-%m-%Y") %>
            </td>
            <td>
              <%= project.end_date.strftime("%d-%m-%Y") %>
            </td>
            <td>
              <% if project.activities.count > 0 %>
                <%=  project.porcentage  %>%
              <% else %>
                0%
              <% end %>
            </td>
            <td>
              <%= project.late? ? "Sim" : "Não" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</section>

app/views/projects/show.html.erb
<section class="wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
      </h3>
      <%=  render 'layouts/messages' %>
      <ol class="breadcrumb">
        <li><i class="fa fa-home mx-2"></i>Home</li>
        <li><i class="fa fa-laptop me-2"></i><%= @project.name %></li>
        <%= link_to new_project_path do %>
          <li class="btn btn-outline-success ms-3 btn-lg"><i class="fa fa-plus me-2 text-success"></i>Novo projeto</li>
        <% end %>
      </ol>
    </div>
  </div>
  <table class="table table-hover text-dark mb-0 bg-white ">
    <thead>
      <tr>
        <th>Nome do Projeto</th>
        <th>Data de Inicio</th>
        <th>Data de Termino</th>
        <th>%Completo</th>
        <th>Atrasado?</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @project.name %></td>
        <td><%= @project.start_date.strftime("%d-%m-%Y")  %></td>
        <td><%= @project.end_date.strftime("%d-%m-%Y") %></td>
        <td>
          <% if @project.activities.count > 0 %>
            <%=  @project.porcentage  %>%
          <% else %>
            0%
          <% end %>
        </td>
        <td>
          <%= @project.late? ? "Sim" : "Não" %>
        </td>
        <td>
          <%= link_to "Apagar", @project, method: :delete, class: "btn  btn-lg btn-outline-danger", data: {confirm: "Tem certeza?"} %>
        </td>
      </tr>
    </tbody>
  </table>
  <table class="table table-hover text-dark mb-0 bg-white ">
    <thead>
      <tr>
        <th>Nome da Atividade</th>
        <th>Data de Inicio</th>
        <th>Data de Termino</th>
        <th>Finalizada?</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @project.activities.each do |activity| %>
        <tr>
          <td>
            <%= activity.name_activity %>
          </td>
          <td><%= activity.start_date.strftime("%d-%m-%Y")  %></td>
          <td><%= activity.end_date.strftime("%d-%m-%Y") %></td>
          <td>
            <%= activity.finished ? "Sim" : "Não" %>
          </td>
          <td>
            <%= link_to  activity_path(activity), method: :put do %>
              <i class="fa fa-exchange-alt mx-3 fs-3"></i>
            <% end %>
            <%= link_to activity, method: :delete, data: {confirm: "Tem certeza?"} do %>
              <i class="fa fa-window-close text-danger fs-3"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show text-start" role="alert">
    <h4 class="alert-heading">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 bi" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </svg>
      Os seguintes erros impediram a criação:
    </h4>
    <ul>
      <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/welcome/teste.html.erb
<h1>OLA MUNDO</h1>